---
name: Build

on:
  push:
    branches:
      - main
  pull_request:

env:
  ARCHITECTURES: '["amd64", "aarch64"]'
  IMAGE_NAME: ha-pihole

permissions:
  contents: read

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - name: Get build matrix
        id: matrix
        uses: home-assistant/builder/actions/prepare-multi-arch-matrix@2026.06.0
        with:
          architectures: ${{ env.ARCHITECTURES }}
          image-name: ${{ env.IMAGE_NAME }}

  build:
    name: Build ${{ matrix.arch }} image
    needs: init
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v6
      - name: Build image
        uses: home-assistant/builder/actions/build-image@2026.06.0
        with:
          arch: ${{ matrix.arch }}
          context: ./pihole
          image: ${{ matrix.image }}
          image-tags: dev
          version: dev
          push: "false"
          cosign: "false"
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
